# Form implementation generated from reading ui file 'pyqt.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_screen1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_screen1.setGeometry(QtCore.QRect(200, 490, 181, 71))
        self.button_screen1.setObjectName("button_screen1")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(120, 40, 991, 401))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.stackedWidget.setLineWidth(4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(30, 10, 211, 101))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(720, 130, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.page_2)
        self.textEdit.setGeometry(QtCore.QRect(103, 110, 531, 141))
        self.textEdit.setObjectName("textEdit")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("background-color: rgb(255, 53, 245);")
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.button_screen3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_screen3.setGeometry(QtCore.QRect(530, 490, 181, 71))
        self.button_screen3.setObjectName("button_screen3")
        self.button_screen2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_screen2.setGeometry(QtCore.QRect(860, 490, 181, 71))
        self.button_screen2.setObjectName("button_screen2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_screen1.setText(_translate("MainWindow", "man 1"))
        self.label.setText(_translate("MainWindow", "deo on r"))
        self.pushButton.setText(_translate("MainWindow", "Bam vao day"))
        self.button_screen3.setText(_translate("MainWindow", "man 2"))
        self.button_screen2.setText(_translate("MainWindow", "man 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
