# Form implementation generated from reading ui file 'pyqt.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 720)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 10, 691, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.button_themdong = QtWidgets.QPushButton(self.centralwidget)
        self.button_themdong.setGeometry(QtCore.QRect(50, 500, 151, 81))
        self.button_themdong.setObjectName("button_themdong")
        self.button_xoadong = QtWidgets.QPushButton(self.centralwidget)
        self.button_xoadong.setGeometry(QtCore.QRect(250, 500, 171, 81))
        self.button_xoadong.setObjectName("button_xoadong")
        self.button_doc = QtWidgets.QPushButton(self.centralwidget)
        self.button_doc.setGeometry(QtCore.QRect(460, 500, 171, 81))
        self.button_doc.setObjectName("button_doc")
        self.button_themcot = QtWidgets.QPushButton(self.centralwidget)
        self.button_themcot.setGeometry(QtCore.QRect(50, 590, 171, 71))
        self.button_themcot.setObjectName("button_themcot")
        self.buttom_xoacot = QtWidgets.QPushButton(self.centralwidget)
        self.buttom_xoacot.setGeometry(QtCore.QRect(260, 590, 171, 71))
        self.buttom_xoacot.setObjectName("buttom_xoacot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1206, 21))
        self.menubar.setObjectName("menubar")
        self.menutoool = QtWidgets.QMenu(self.menubar)
        self.menutoool.setObjectName("menutoool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionvcl = QtGui.QAction(MainWindow)
        self.actionvcl.setObjectName("actionvcl")
        self.actionvcl2 = QtGui.QAction(MainWindow)
        self.actionvcl2.setObjectName("actionvcl2")
        self.actionvcl3 = QtGui.QAction(MainWindow)
        self.actionvcl3.setObjectName("actionvcl3")
        self.menutoool.addAction(self.actionvcl)
        self.menutoool.addAction(self.actionvcl2)
        self.menutoool.addAction(self.actionvcl3)
        self.menubar.addAction(self.menutoool.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_themdong.setText(_translate("MainWindow", "Thêm dòng"))
        self.button_xoadong.setText(_translate("MainWindow", "Xóa dòng"))
        self.button_doc.setText(_translate("MainWindow", "đọc"))
        self.button_themcot.setText(_translate("MainWindow", "thêm cột"))
        self.buttom_xoacot.setText(_translate("MainWindow", "Xóa cột"))
        self.menutoool.setTitle(_translate("MainWindow", "toool"))
        self.actionvcl.setText(_translate("MainWindow", "vcl"))
        self.actionvcl2.setText(_translate("MainWindow", "vcl2"))
        self.actionvcl3.setText(_translate("MainWindow", "vcl3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
